from pydantic import BaseModel, Field


class SilverRedditNodeSummarization(BaseModel):
    reddit_node_id: str = Field(description="Unique node identifier for the subreddit submission or comment")
    summary: str = Field(description="The summarized text generated by the AI model")
    prompt_tokens: int = Field(description="Number of prompt tokens used")
    completion_tokens: int = Field(description="Number of completion tokens generated")
    cost_usd: float = Field(description="Calculated cost of the LLM call based on the pricing model")
